include(
    "app",
    "common-message",
    "common-protobuf",
    "common-serialization-protobuf",
    "receiver-files",
    "receiver-files-default",
    "receiver-serialization",
    "receiver-serialization-protobuf",
    "sender-files",
    "sender-files-buffered",
    "sender-serialization",
    "sender-serialization-protobuf"
)
