include(
    "app",
    "message",
    "protobuf",
    "serialization-sender",
    "serialization-receiver",
    "serialization-protobuf",
    "serialization-protobuf-common",
    "serialization-protobuf-sender",
    "serialization-protobuf-receiver"
)
